### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mzaini30** [rixo/svelte-template-hot#14]
```
RangeError: Maximum call stack size exceeded
    at callAsyncFirstHook (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginLifecycle.js:34:24)
    at Object.resolveId (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginLifecycle.js:129:28)
    at Object.resolve (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginContext.js:117:64)
    at Object.resolveId (/home/zen/Documents/psikotes/node_modules/.pnpm/@rollup/plugin-commonjs@14.0.0_rollup@2.32.1/node_modules/@rollup/plugin-commonjs/dist/index.js:1131:17)
    at _callAsyncHook (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginLifecycle.js:12:31)
    at callAsyncFirstHook (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginLifecycle.js:34:24)
    at Object.resolveId (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginLifecycle.js:129:28)
    at Object.resolve (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginContext.js:117:64)
    at Object.resolveId (/home/zen/Documents/psikotes/node_modules/.pnpm/@rollup/plugin-commonjs@14.0.0_rollup@2.32.1/node_modules/@rollup/plugin-commonjs/dist/index.js:1131:17)
    at _callAsyncHook (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginLifecycle.js:12:31)
RangeError: Maximum call stack size exceeded
    at callAsyncFirstHook (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginLifecycle.js:34:24)
    at Object.resolveId (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginLifecycle.js:129:28)
    at Object.resolve (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginContext.js:117:64)
    at Object.resolveId (/home/zen/Documents/psikotes/node_modules/.pnpm/@rollup/plugin-commonjs@14.0.0_rollup@2.32.1/node_modules/@rollup/plugin-commonjs/dist/index.js:1131:17)
    at _callAsyncHook (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginLifecycle.js:12:31)
    at callAsyncFirstHook (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginLifecycle.js:34:24)
    at Object.resolveId (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginLifecycle.js:129:28)
    at Object.resolve (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginContext.js:117:64)
    at Object.resolveId (/home/zen/Documents/psikotes/node_modules/.pnpm/@rollup/plugin-commonjs@14.0.0_rollup@2.32.1/node_modules/@rollup/plugin-commonjs/dist/index.js:1131:17)
    at _callAsyncHook (/home/zen/Documents/psikotes/node_modules/.pnpm/nollup@0.13.13_rollup@2.32.1/node_modules/nollup/lib/impl/PluginLifecycle.js:12:31)
```

**Comment by mzaini30** [comment]
I think the error is in my code
